[workspace]
members = ["crates/types", "contracts/ckb-combine-lock", "contracts/child-script-example", "contracts/child-script-always-success", "contracts/child-script-always-failure", "contracts/global-registry", "contracts/lock-wrapper"]

[profile.release]
overflow-checks = true
opt-level = 3
panic = 'abort'
strip = true
lto = true
debug-assertions = true

[profile.dev]
strip = true
opt-level = 1
debug = false
panic = 'abort'
debug-assertions = true
